// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpnimyfplhalqidzustl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwbmlteWZwbGhhbHFpZHp1c3RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjgwMDEsImV4cCI6MjA2NDYwNDAwMX0.DyDpLoshIj4LR0RhfEX5_jY6wh0Tao5xGpPpoFZ1bJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);